# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-13 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0003_auto_20160902_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleetapp.Vehicle'),
        ),
    ]
